Added find_if and find_if_not tests
tcbrindle/flux pull request #212
Opened 2024-11-04 19:00 UTC by nwad123

Resolves #194

2024-11-04 19:13 UTC, nwad123 commented
Hi! This is my first time attempting to contribute to a project on GitHub so if I'm doing anything wrong please let me know! I followed some instructions I found online for submitting a pull request, and I'm not actually confident that I did it right, so if there is a better process I'd love to get a quick walkthrough.

2024-11-05 12:33 UTC, tcbrindle requested changes
This is very comprehensive, thank you! Just a couple of little comments -- the function statically testing `find_if_not()` should be called `test_find_if_not()`, and we want to run the static test functions at runtime as well.

Other than that, this looks great!

2024-11-05 12:33 UTC, tcbrindle commented on test/test_find_if_not.cpp
> +constexpr bool test_find_if()
This is testing `find_if_not()` :)

```suggestion
constexpr bool test_find_if_not()
```

2024-11-05 12:33 UTC, tcbrindle commented on test/test_find_if_not.cpp
> +static_assert(test_find_if());
```suggestion
static_assert(test_find_if_not());
```

2024-11-05 12:33 UTC, tcbrindle commented on test/test_find_if.cpp
> +    }
We want to run the static tests at runtime as well, so we need to include them in the `TEST_CASE` block

```suggestion
    REQUIRE(test_find_if());

    {
        std::vector<int> vec {1, 2, 3, 4, 5};
        auto is_greater_than_3 = [](int x) { return x > 3; };
        auto idx = flux::find_if(vec, is_greater_than_3);
        REQUIRE(idx == 3);
    }
```

2024-11-05 12:33 UTC, tcbrindle commented on test/test_find_if_not.cpp
> +    }
As above, we want to run the static test in the `TEST_CASE` block here as well

```suggestion

    REQUIRE(test_find_if_not());

    {
        std::vector<int> vec {1, 2, 3, 4, 5};
        auto is_odd = [](int x) { return x % 2 == 1; };
        auto idx = flux::find_if_not(vec, is_odd);
        REQUIRE(idx == 1);
    }
```

2024-11-05 17:18 UTC, tcbrindle approved these changes

2024-11-05 17:18 UTC, merged

2024-11-05 17:19 UTC, tcbrindle commented
Merged, thank you very much @nwad123!